given_sentence = input("Give me a sentence: ")
print("The sentence you gave was: " + given_sentence)
original_word = input("What word would you like to replace? ")
new_word = input("What is the new word? ")
print(given_sentence.replace(original_word,new_word))
